import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Solar Book',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <div class="w-screen bg-gray-800 px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div>
        <span class="text-green-600 text-3xl font-mono font-bold"> SOLAR</span>
        <span class="text-white text-2xl font-mono font-bold">BOOK</span>
        <img href="/" class="h-28 w-28 inline" src="/LOGO.png" alt="Your Company"></img>
        </div>
        <div class="flex items-center">
          <div class="flex-shrink-0">
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <a href="#" class="bg-gray-900 text-white hover:text-green-600 rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Charge Your EV Now</a>
              <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-green-600 rounded-md px-3 py-2 text-sm font-medium">How It Works</a>
              <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-green-600 rounded-md px-3 py-2 text-sm font-medium">Services</a>
              <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-green-600 rounded-md px-3 py-2 text-sm font-medium">Become EV Provider</a>
              <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-green-600 rounded-md px-3 py-2 text-sm font-medium">Contact Us</a>
            </div>
          </div>
        </div>
        <div class="hidden md:block">
          <div class="mr-100 flex items-center md:ml-5 space-x-2">
            <a href="/register" class="text-gray-300 hover:bg-gray-700 hover:text-green-600 rounded-md px-3 py-2 text-sm font-medium">Register</a>
            <a href="/login" class="bg-green-600 text-gray-300 hover:bg-gray-700 hover:text-green-600 rounded-md px-3 py-2 text-sm font-medium">Login</a>
            <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">View notifications</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
              </svg>
            </button>

            
            <div class="relative ml-3">
              <div>
                <button type="button" class="relative flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                  <span class="absolute -inset-1.5"></span>
                  <span class="sr-only">Open user menu</span>
                  
                </button>
              </div>

      
              <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
              
                <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
              </div>
            </div>
          </div>
        </div>
        <div class="-mr-2 flex md:hidden">
        
          <button type="button" class="relative inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" aria-controls="mobile-menu" aria-expanded="false">
            <span class="absolute -inset-0.5"></span>
            <span class="sr-only">Open main menu</span>
            
            <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
            
            <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div> */}
        
        {children}</body>
    </html>
  )
}


